services:
  # Create a redis instance
  - type: redis
    name: team-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: []

  # Let's create our background worker
  - type: worker
    name: team-worker
    env: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec phase-3-sinatra-react-project/app/controllers -r ./teams_controller.rb
    autoDeploy: false
    envVars:
      - key: redis://red-ced8du14reb894314pfg:6379
        fromService:
          type: redis
          name: team-redis
          property: connectionString

  # Create the web server hosting sinatra
  - type: web
    name: sinatra-web
    env: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec ruby app/controllers/teams_controller.rb
    autoDeploy: false
    envVars:
      - key: redis://red-ced8du14reb894314pfg:6379
        fromService:
          type: redis
          name: team-redis
          property: connectionString